version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      CLERK_ISSUER: ${CLERK_ISSUER}
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
